# First Github action workflow

name: App Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read # Allow to read content on remote repository

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # run: git clone https://github.com/zark-stark12/MLE.git . # Run bash command
      uses: actions/checkout@v5 # this does the same as the git clone bash command above https://github.com/actions/checkout

    - name: Setup python
      uses: actions/setup-python@v5 # uses github action workflow
      with:
        python-version: '3.13.5'

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH=$HOME/.local/bin:$PATH

    - name: Install dependencies using poetry
      run: poetry run make install

    # - name: Lint checker with flake8
    #  run: poetry run make check

